INSERT INTO CDL (
    SafetyCert,
    SystemAffected,
    Location,
    SpecLoc,
    Status,
    Severity,
    DueDate,
    GroupToResolve,
    RequiredBy,
    contractID,
    IdentifiedBy,
    defType,
    Description,
    Spec,
    ActionOwner,
    OldID,
    Comments,
    EvidenceType,
    Repo,
    EvidenceLink,
    ClosureComments,
    Created_by,
    DateCreated,
    DateClosed
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)