<?php
include('session.php');
include('html_functions/bootstrapGrid.php');
include('filestart.php');

$title = "SVBX - Update BART Deficiency";

$defID = $_GET['bartDefID'];
$fieldList = file_get_contents('bartdl.sql');
$fieldsArr = array_fill_keys(explode(',', $fieldList), '?');
unset($fieldsArr['ID']); // unset ID b/c it will be generated by MySQL
$fieldList = implode(',', array_keys($fieldsArr));
$sql = "SELECT $fieldList FROM BARTDL WHERE id=$defID";

$link = f_sqlConnect();

if ($result = $link->query('SELECT bdPermit from users_enc where userID='.$_SESSION['UserID'])) {
    if ($row = $result->fetch_row()) {
        $bdPermit = $row[0];
    }
    $result->close();
}

include('filestart.php');

if ($stmt = $link->prepare($sql)) {
    echo "
        <div style='margin-top: 3.5rem; color: paleVioletRed'>
            <p>$sql</p>";
    echo "</div>";
} else {
    echo "<pre style='margin-top: 3.5rem; color: fuchsia'>{$link->error}</pre>";
    $link->close();
    exit;
}

$link->close();
include('fileend.php');
