SELECT 
    oldID,
    location,
    specLoc,
    severity,
    description,
    spec,
    DATE_FORMAT(dateCreated, "%d %b %Y"),
    status,
    identifiedBy,
    systemAffected,
    groupToResolve,
    actionOwner,
    evidenceType,
    evidenceLink,
    dateClosed,
    lastUpdated,
    updated_by,
    comments,
    requiredBy,
    contractID,
    repo,
    closureComments,
    dueDate,
    safetyCert,
    defType
FROM
    CDL
Where DefID=